commit_message: '[skip ci]'
pull_request_title: 'i18n: update translations'
pull_request_labels:
  - i18n
files:
  - source: /zh-CN/**/*.md
    translation: /%locale%/**/%file_name%.md
    ignore:
      - /zh-CN/contribute/docs.md
  - source: /**/zh-CN.json
    translation: /**/%locale%.json
